publishers:
  - queueName: json-queue
    contentType: json
    identities:
      - Alice
      
consumers:
  - queueName: json-queue
    identities:
      - Alice

identities:
  - name: Alice
    token: SuperSecretToken123